cambios en el fronend.yml

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -99,10 +99,19 @@ jobs:
 
       - name: Confirm build folder exists
         run: |
-          if [ ! -d "dist/frontend/browser" ]; then
-            echo "Error: dist/frontend/browser does not exist. Build failed?"
+          if [ ! -d "dist/frontend/browser/browser" ]; then
+            echo "Error: dist/frontend/browser/browser does not exist. Build failed?"
             exit 1
           fi
+
+      - name: Move build files to expected folder
+        run: |
+          # Vaciar dist/frontend/browser
+          rm -rf dist/frontend/browser/* || true
+          # Mover los archivos de la carpeta interna 'browser'
+          mv dist/frontend/browser/browser/* dist/frontend/browser/
+          # Eliminar la carpeta interna vacía
+          rmdir dist/frontend/browser/browser
 
       - name: Deploy to Firebase Staging
         run: firebase deploy --project ${{ vars.FIREBASE_PROJECT_STAGING }} --token ${{ secrets.FIREBASE_TOKEN }} --only hosting
@@ -121,7 +130,6 @@ jobs:
             fi
             echo "Firebase site is live and healthy (status: $STATUS)"
           fi
-
   frontend-status:
     name: Frontend CI/CD Status
     runs-on: ubuntu-latest
